name: GitHub Actions Secret Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  secrets-in-github-action:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions secret to the logs
        run: |
          echo " The GH Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo " Trick to echo GH Action Secret: "
          echo ${{ secrets.SECRET_TOKEN }} |sed 's/./& /g'

      - name: Step 2 - GH Action if statement (true)
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST == 'Trust No 1'
        run: echo "I got it"


      - name: Step 3  - Conditional GH Action (false)
        shell: bash
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST != 'TrustNoBody'
        run: echo "I was wrong thinking the GitHub secret was 'TrustNoBody'!"
        
