name: GitHub Actions Secret Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  secrets-in-github-action:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions secret to the logs
        run: |
          echo " The GH Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo " Trick to echo GH Action Secret: "
          echo ${{ secrets.SECRET_TOKEN }} |sed 's/./& /g'
