# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 1. What is in this directory?
          echo
          ls -a
          echo
          echo 2. Is jave installed?
          echo
          java -version
          echo
          echo 3. Is Git installed?
          echo
          git --version
          echo
          echo 4. What about build tools?
          echo
          mvn --version
          echo
          gradle --version
          echo
          ant -version
          echo
          echo 5. Where is the Android SDK root?
          echo 
          echo $ANDROID_SDK_ROOT
          echo
          echo 6. Where are the Selenium jars?
          echo
          echo $SELENIUM_JAR_PATH
          echo
          echo 7. What is the workspace location?
          echo
          echo $RUNNER_WORKSPACE
          echo 
          echo 8. Who is running the script?
          echo
          whoami
          echo
          echo 9. How is the disk laid out?
          echo
          df -hT
          echo
          echo 10. What environment variables are available?
          echo
          env
